### ISSUE TITLE
Papi-Bot reintroduces itself after some server outages

### ISSUE THREAD

**Issue by Emosewaj** [Jawesome99/papibot#11]
Whenever Discord has one of it's outages, the bot beliefes it was removed and then readded to several guilds, making it reintroduce itself.

Fix: Check new server against list of known servers and only send introduction if server is unknown.

**Comment by devdutchy** [comment]
Should check the `guild.available` property (https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=available), if it returns false it indicates an outage

**Comment by Emosewaj** [comment]
That's less of an issue, the problem is rather that the bot falsely receives `guildDelete` and `guildCreate` events as if removed/added from/to a guild.

**Comment by devdutchy** [comment]
> the problem is rather that the bot falsely receives guildDelete and guildCreate events as if removed/added from/to a guild.

This is what I mean by checking the `guild.available` property, if you check if that property isn't false before running the rest of the code in the listener, it won't reintroduce itself as it indicated an outage.

**Comment by Emosewaj** [comment]
Put on hold until I re-implement the feature.

**Comment by Emosewaj** [comment]
Most likely won't be reimplementing.
